# Generated by Django 4.1.3 on 2022-11-17 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Network name')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Wallet address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_network', to='crypto_wallet.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crypto_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Token name')),
                ('symbol', models.CharField(max_length=25, verbose_name='Token symbol')),
                ('token_address', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Token address')),
                ('decimals', models.IntegerField(default=8, verbose_name='Decimals')),
                ('extra', models.JSONField(blank=True, default=None, null=True, verbose_name='Extra')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_network', to='crypto_wallet.network')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Token',
            },
        ),
        migrations.CreateModel(
            name='InternalTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.UUID('9eef07b0-3529-43a8-8479-0af266c2218b'), primary_key=True, serialize=False, verbose_name='Internal transaction ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Amount')),
                ('fee', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Commission')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('recipient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipient_wallet_crypto_internal_transaction', to='crypto_wallet.wallet')),
                ('sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender_wallet_crypto_internal_transaction', to='crypto_wallet.wallet')),
            ],
            options={
                'verbose_name': 'Internal Transaction',
                'verbose_name_plural': 'Internal Transactions',
            },
        ),
        migrations.CreateModel(
            name='ExternalTransactions',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('address', models.CharField(max_length=255, verbose_name='From Wallet address')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Amount')),
                ('fee', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Commission')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('type', models.CharField(choices=[('SENDER', 'Sender transaction'), ('RECIPIENT', 'Recipient transaction')], default='RECIPIENT', max_length=50, verbose_name='User type')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_transaction_token', to='crypto_wallet.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crypto_external_transaction', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_external_transaction', to='crypto_wallet.wallet')),
            ],
            options={
                'verbose_name': 'External Transaction',
                'verbose_name_plural': 'External Transactions',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=8, verbose_name='Amount')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_token', to='crypto_wallet.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crypto_wallet_balance', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balance', to='crypto_wallet.wallet')),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
    ]
